package com.asef.dordambdandroid.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme ────────────────────────────────────────────────────────────
val IndigoPrimary                = Color(0xFF4F46E5)
val IndigoOnPrimary              = Color(0xFFFFFFFF)
val IndigoPrimaryContainer       = Color(0xFFE0E0FF)
val IndigoOnPrimaryContainer     = Color(0xFF00006E)
val IndigoSecondary              = Color(0xFF5A5D72)
val IndigoOnSecondary            = Color(0xFFFFFFFF)
val IndigoSecondaryContainer     = Color(0xFFDFE1F9)
val IndigoOnSecondaryContainer   = Color(0xFF171A2C)
val IndigoTertiary               = Color(0xFF7D5260)
val IndigoOnTertiary             = Color(0xFFFFFFFF)
val IndigoTertiaryContainer      = Color(0xFFFFD8E4)
val IndigoOnTertiaryContainer    = Color(0xFF31111D)
val IndigoError                  = Color(0xFFDC2626)
val IndigoOnError                = Color(0xFFFFFFFF)
val IndigoErrorContainer         = Color(0xFFFFDAD6)
val IndigoOnErrorContainer       = Color(0xFF410002)
val IndigoBackground             = Color(0xFFF8F9FF)
val IndigoOnBackground           = Color(0xFF1A1A1A)
val IndigoSurface                = Color(0xFFF8F9FF)
val IndigoOnSurface              = Color(0xFF1A1A1A)
val IndigoSurfaceVariant         = Color(0xFFE5E7EB)
val IndigoOnSurfaceVariant       = Color(0xFF6B7280)
val IndigoOutline                = Color(0xFFE5E7EB)
val IndigoOutlineVariant         = Color(0xFFC7C4D7)
val IndigoScrim                  = Color(0xFF000000)
val IndigoInverseSurface         = Color(0xFF313031)
val IndigoInverseOnSurface       = Color(0xFFF4F0F1)
val IndigoInversePrimary         = Color(0xFFC0C1FF)

// Custom trend colors for light theme
val LightTrendUp                 = Color(0xFF16A34A)
val LightTrendDown               = Color(0xFFDC2626)

// ── Dark scheme ─────────────────────────────────────────────────────────────
val IndigoPrimaryDark                = Color(0xFFC0C1FF)
val IndigoOnPrimaryDark              = Color(0xFF1000A9)
val IndigoPrimaryContainerDark       = Color(0xFF8083FF)
val IndigoOnPrimaryContainerDark     = Color(0xFF0D0096)
val IndigoSecondaryDark              = Color(0xFFD0BCFF)
val IndigoOnSecondaryDark            = Color(0xFF3C0091)
val IndigoSecondaryContainerDark     = Color(0xFF571BC1)
val IndigoOnSecondaryContainerDark   = Color(0xFFC4ABFF)
val IndigoTertiaryDark               = Color(0xFFFFB783)
val IndigoOnTertiaryDark             = Color(0xFF4F2500)
val IndigoTertiaryContainerDark      = Color(0xFFD97721)
val IndigoOnTertiaryContainerDark    = Color(0xFF452000)
val IndigoErrorDark                  = Color(0xFFFFB4AB)
val IndigoOnErrorDark                = Color(0xFF690005)
val IndigoErrorContainerDark         = Color(0xFF93000A)
val IndigoOnErrorContainerDark       = Color(0xFFFFDAD6)
val IndigoBackgroundDark             = Color(0xFF131314)
val IndigoOnBackgroundDark           = Color(0xFFE5E2E3)
val IndigoSurfaceDark                = Color(0xFF131314)
val IndigoOnSurfaceDark              = Color(0xFFE5E2E3)
val IndigoSurfaceVariantDark         = Color(0xFF353436)
val IndigoOnSurfaceVariantDark       = Color(0xFFC7C4D7)
val IndigoOutlineDark                = Color(0xFF908FA0)
val IndigoOutlineVariantDark         = Color(0xFF464554)
val IndigoScrimDark                  = Color(0xFF000000)
val IndigoInverseSurfaceDark         = Color(0xFFE5E2E3)
val IndigoInverseOnSurfaceDark       = Color(0xFF313031)
val IndigoInversePrimaryDark         = Color(0xFF494BD6)

// Custom trend colors for dark theme
val DarkTrendUp                  = Color(0xFF4ADE80)
val DarkTrendDown                = Color(0xFFF87171)
